doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 80
autodetect: yes
requirements:
    - requirements-dev.txt
ignore-paths:
    - docs
    - tests
ignore-patterns:
    - ^.*_ui.py$
pep8:
    full: true
pylint:
  disable:
    - protected-access
    - too-many-arguments
    - redefined-builtin
    # the disabled warnings should be removed once landscape properly support
    # Py3
    - super-on-old-class
    - old-style-class
    - undefined-variable
