language: python
sudo: required
dist: trusty

python:
  - "3.4"

virtualenv:
  system_site_packages: true

env:
 - PYTEST_QT_API=pyqt5

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
 - sudo apt-get update
 - sudo apt-get install -y -qq python3-pyqt5 python3-pyqt5.qtsvg gnome-icon-theme-full --fix-missing
 - pip install pytest pytest-qt pytest-cov coveralls --upgrade
 # install hackedit
 - pip install -e .
 # install a plugin package to make tests more complete
 - pip install git+https://github.com/HackEdit/hackedit-python.git
 # needed for the i18n tests
 - python setup.py install_data

script:
 - catchsegv py.test --cov hackedit

after_success:
 - coveralls
