environment:
    matrix:
        - PYTHON: "C:\\Python34"
          PYTHON_VERSION: "3.4.x" # currently 3.4.3
          PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python34-x64"
          PYTHON_VERSION: "3.4.x" # currently 3.4.3
          PYTHON_ARCH: "64"

install:
  - python -u scripts\install-qt.py
  - python -m pip install pytest pytest-qt pytest-cov coveralls --upgrade
  - python -m pip install -e .

test_script:
  # Run the project tests
  - py.test
