environment:
    matrix:
        - PYTHON: "C:\\Python34"
          PYTHON_VERSION: "3.4.x" # currently 3.4.3
          PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python34-x64"
          PYTHON_VERSION: "3.4.x" # currently 3.4.3
          PYTHON_ARCH: "64"

install:
  # Prepend newly installed Python to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  # Install pyqt
  - python -u scripts\install-qt.py
  # Update pip and setuptools
  - python -m pip install --upgrade pip setuptools
  # Install pytest and pytest-qt
  - pip install pytest pytest-qt
  # install hackedit in development mode
  - pip install -e .

build: false  # Not a C# project

test_script:
  # Run the project tests
  - py.test
